import type { NextPage } from 'next';
import Head from 'next/head';
import { Poster } from '../src/components/Poster';
import styles from '../styles/Home.module.css';
import { InTheathers } from './styles';
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

// import required modules
import { Navigation, Pagination } from 'swiper';
import Carousel from '../src/components/Carousel';

const Home: NextPage = () => {
  const moviePosters = [
    {
      title: 'A Mulher Rei',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/a-mulher-rei/ee8d3ab4-8143-4385-a135-b8c442360295.jpg',
    },
    {
      title: 'Sorria',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/sorria/3472ec57-707a-4434-93b8-c0e6694b7898.jpg',
    },
    {
      title: 'Avatar',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/avatar/28c9f1f7-dedc-47c3-b2c7-4a5d6e31ea1f.jpg',
    },
    {
      title: 'Minions 2',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/minions-2-a-origem-de-gru/e7a253ca-298b-419b-acbe-4abc8fd563e9.jpg',
    },
    {
      title: 'Halloween Ends',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/halloween-ends/d690e49a-4348-47b1-966a-be0f268d301a.jpg',
    },
    {
      title: 'Liga dos SuperPets',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/a-liga-dos-superpets/a1903023-8faf-4a74-a09a-9068b0ba3d93.jpg',
    },
    {
      title: 'Adão Negro',
      imgUrl:
        'https://ingresso-a.akamaihd.net/prd/img/movie/adao-negro/ead75dcb-957f-4f35-8065-b4924206625a.jpg',
    },
  ];
  const renderTheather = () => {
    return (
      <InTheathers>
        <p className="header">Em Cartaz</p>
        <Swiper
          breakpoints={{
            100: {
              slidesPerView: 1,
            },
            550: {
              slidesPerView: 2,
            },
            768: {
              slidesPerView: 3,
            },
            1000: {
              slidesPerView: 4,
            },
            1200: {
              slidesPerView: 5,
            },
            1440: {
              slidesPerView: 5,
            },
          }}
          navigation={true}
          modules={[Navigation]}
          className="mySwiper"
          slidesPerView={5}
          centerInsufficientSlides
        >
          {moviePosters.map(({ title, imgUrl }, index) => (
            <SwiperSlide key={index}>
              <Poster key={index} title={title} imgUrl={imgUrl} />
            </SwiperSlide>
          ))}
        </Swiper>
      </InTheathers>
    );
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div
        style={{
          padding: '3rem 3rem 3rem 3rem',
          background: 'rgba(13, 0, 28, 0.833)',
        }}
      >
        <Carousel />
      </div>
    </div>
  );
};

export default Home;
